export const API = {
  products: "/products",
  product: (id: string) => `/products/${id}`,
  productBySlug: (slug: string) => `/products/slug/${slug}`,
  categories: "/categories",
  brands: "/brands",
  cart: "/cart",
  cartItem: (id: string) => `/cart/items/${id}`,
  wishlist: "/wishlist",
  orders: "/orders",
  order: (id: string) => `/orders/${id}`,
  me: "/auth/me",
  addresses: "/addresses",
  reviews: (productId: string) => `/products/${productId}/reviews`,
  verifyCoupon: "/coupons/verify",
  checkout: "/checkout",
  adminStats: "/admin/stats",
  adminProducts: "/admin/products",
  adminProduct: (id: string) => `/admin/products/${id}`,
  adminCategories: "/admin/categories",
  adminBrands: "/admin/brands",
  adminCoupons: "/admin/coupons",
  adminOrders: "/admin/orders",
  adminOrder: (id: string) => `/admin/orders/${id}`,
  adminCustomers: "/admin/customers",
  adminInventory: "/admin/inventory",
  adminReviews: "/admin/reviews",
} as const;
