export const ROUTES = {
  home: "/",
  products: "/products",
  product: (slug: string) => `/products/${slug}`,
  category: (slug: string) => `/categories/${slug}`,
  categories: "/categories",
  search: "/search",
  cart: "/cart",
  wishlist: "/wishlist",
  checkout: "/checkout",
  orderSuccess: (id: string) => `/checkout/success?orderId=${id}`,
  login: "/auth/login",
  register: "/auth/register",
  forgotPassword: "/auth/forgot-password",
  account: "/account",
  profile: "/account/profile",
  orders: "/account/orders",
  orderDetail: (id: string) => `/account/orders/${id}`,
  addresses: "/account/addresses",
  accountWishlist: "/account/wishlist",
  admin: "/admin",
  adminProducts: "/admin/products",
  adminProductNew: "/admin/products/new",
  adminProductEdit: (id: string) => `/admin/products/${id}/edit`,
  adminCategories: "/admin/categories",
  adminBrands: "/admin/brands",
  adminCoupons: "/admin/coupons",
  adminOrders: "/admin/orders",
  adminCustomers: "/admin/customers",
  adminInventory: "/admin/inventory",
  adminReviews: "/admin/reviews",
} as const;
